### ISSUE TITLE
Error on transitioning issue: TypeError: opts.fields.forEach is not a function

### ISSUE THREAD

**Issue by Mustek** [floralvikings/jira-connector#15]
Hi,

Trying to transition an issue to be resolved as invalid.
This is my testcode where issue is the issue key:

ID 5 is "Resolve"

```
function resolve_invalid(issue) {
    jira.issue.transitionIssue({
        issueKey:   issue,
        transition: {id: '5'},
        fields: {resolution: {name: 'Invalid'}}
    }, function (error, data) {
        console.log(error);
        console.log(data);
    });
}
```

Error without the fields is 'Missing \'transition\' identifier'
According to the Jira REST API, the fields object is supported.

Example:

```
{
    "update": {
        "comment": [
            {
                "add": {
                    "body": "Bug has been fixed."
                }
            }
        ]
    },
    "fields": {
        "assignee": {
            "name": "bob"
        },
        "resolution": {
            "name": "Fixed"
        }
    },
    "transition": {
        "id": "5"
    },
    "historyMetadata": {
        "type": "myplugin:type",
        "description": "text description",
        "descriptionKey": "plugin.changereason.i18.key",
        "activityDescription": "text description",
        "activityDescriptionKey": "plugin.activity.i18.key",
        "actor": {
            "id": "tony",
            "displayName": "Tony",
            "type": "mysystem-user",
            "avatarUrl": "http://mysystem/avatar/tony.jpg",
            "url": "http://mysystem/users/tony"
        },
        "generator": {
            "id": "mysystem-1",
            "type": "mysystem-application"
        },
        "cause": {
            "id": "myevent",
            "type": "mysystem-event"
        },
        "extraData": {
            "keyvalue": "extra data",
            "goes": "here"
        }
    }
}
```

Stacktrace:
```
TypeError: opts.fields.forEach is not a function
    at IssueClient.buildRequestOptions (c:\Users\muste\WebstormProjects\arise\node_modules\jira-connector\api\issue.js:981:25)
    at IssueClient.transitionIssue (c:\Users\muste\WebstormProjects\arise\node_modules\jira-connector\api\issue.js:580:28)
```

**Comment by Mustek** [comment]
Added stacktrace to the bottom.

**Comment by Mustek** [comment]
Seems like that's actually for the fields filter (used in search).

This fixed it:

'''
function resolve_invalid(issue) {
    jira.issue.transitionIssue({
        issueKey:   issue,
        transition: {
            transition: {id: 5},
            fields: {resolution: {name: 'Invalid'}},
            update: {comment:[ { add: {body: "Comment."}}]}
        }
    }, function (error, data) {
        console.log(error);
        console.log(data);
    });
}
'''
