### ISSUE TITLE
Client not working via https

### ISSUE THREAD

**Issue by artkrz** [floralvikings/jira-connector#26]
Hi,

I can not get the library to connect via https:

```javascript
var JiraClient = require('./index.js');

var jira = new JiraClient({
    host: 'jira.foo.bar',
    oauth: {
        consumer_key: '...',
        token: '...',
        token_secret: '...',
        private_key: '-----BEGIN RSA PRIVATE KEY-----\n' +
        '...\n' +
        '-----END RSA PRIVATE KEY-----'
    }
});

jira.issue.getIssue({
    issueKey: 'T-1'
}, function(error, issue) {
    console.log(issue.fields.summary);
});
```

When I run it:

```
$ node test.js

TypeError: Cannot read property 'fields' of undefined
    at /home/hubot/node_modules/hubot-jira-connector/node_modules/jira-connector/test.js:30:22
    at Request._callback (/home/hubot/node_modules/hubot-jira-connector/node_modules/jira-connector/index.js:260:24)
    at Request.self.callback (/home/hubot/node_modules/hubot-jira-connector/node_modules/jira-connector/node_modules/request/request.js:199:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/home/hubot/node_modules/hubot-jira-connector/node_modules/jira-connector/node_modules/request/request.js:1036:10)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/home/hubot/node_modules/hubot-jira-connector/node_modules/jira-connector/node_modules/request/request.js:963:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

however, when I use http it works fine:

```javascript
var JiraClient = require('./index.js');

var jira = new JiraClient({
    host: 'jira.foo.bar',
    protocol: 'http',
    oauth: {
        consumer_key: '...',
        token: '...',
        token_secret: '...',
        private_key: '-----BEGIN RSA PRIVATE KEY-----\n' +
        '...\n' +
        '-----END RSA PRIVATE KEY-----'
    }
});

jira.issue.getIssue({
    issueKey: 'T-1'
}, function(error, issue) {
    console.log(issue.fields.summary);
});
```

```
$ node test.js
Test ticket
```

Curl doesn't show any certificate errors:

```
$ curl -v https://jira.foo.bar/rest/api/2/issue/T-1
*   Trying 54.x.x.x...
* Connected to jira.foo.bar (54.x.x.x) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=*.foo.bar,O="Amazon.com, Inc.",L=Seattle,ST=Washington,C=US
* 	start date: Sep 14 00:00:00 2015 GMT
* 	expire date: Nov 04 23:59:59 2016 GMT
* 	common name: *.foo.bar
* 	issuer: CN=Symantec Class 3 Secure Server CA - G4,OU=Symantec Trust Network,O=Symantec Corporation,C=US
> GET /rest/api/2/issue/T-1 HTTP/1.1
> User-Agent: curl/7.40.0
> Host: jira.foo.bar
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.8.1
< Date: Wed, 09 Mar 2016 08:12:09 GMT
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-AREQUESTID: 492x2054338x1
< X-ASEN: SEN-4281670
< Set-Cookie: atlassian.xsrf.token=BLTD-G3C4-QIZQ-HKFG|9fd33f69c1caaecece6f5fe3f40dfca53b30daec|lout; Path=/
< X-AUSERNAME: anonymous
< Cache-Control: no-cache, no-store, no-transform
< X-Content-Type-Options: nosniff
< WWW-Authenticate: OAuth realm="http%3A%2F%2Fjira.foo.bar"
<
* Connection #0 to host jira.foo.bar left intact
{"errorMessages":["You do not have the permission to see the specified issue.","Login Required"],"errors":{}}
```

Any ideas what's happening here ?

**Comment by floralvikings** [comment]
Hmm... In your https testing code, can you log the `error` parameter of the callback?  It looks like you're getting the `TypeError` because the `issue` parameter is undefined, but I'm not sure why that would be.

Also, if you're on version 2.0.0 of jira-connector, you should be able to change the callback function to this, to get a better idea of what's going on:

```javascript
function(error, issue, response) {
    console.log(error);
    console.log(response);
    console.log(issue.fields.summary);
}
```

**Comment by artkrz** [comment]
Thanks for replying. Here's the error output (i removed parts of it to protect my credentials):

```
oauth_signature=...&oauth_signature_base_string=GET%26http%253A%252F%252Fjira.foo.bar%252Frest%252Fapi%252F2%252Fissue%252FT-1%26oauth_consumer_key%...%2526oauth_nonce%...%2526oauth_signature_method%253DRSA-SHA1%2526oauth_timestamp%253D1457596661%2526oauth_token%...%2526oauth_version%253D1.0&oauth_problem=signature_invalid&oauth_signature_method=RSA-SHA1
```

**Comment by floralvikings** [comment]
Ok; I'll set up a testing JIRA project and see if I can figure out what's going on.  I probably won't have time to get to it until this weekend, though.  I'll keep you posted.

**Comment by artkrz** [comment]
I've solved it. Looks like it was caused by bad config of SSL and reverse proxy. After enforcing SSL and fixing the setup as advised by JIRA notification to add reverse proxy details into catalina config, everything works fine. Thanks.
