### ISSUE TITLE
Client not working via http://ip:port 

### ISSUE THREAD

**Issue by yamazakei321** [floralvikings/jira-connector#41]
Hi,

My jira url is http://ip:8080 I can not get the connect to jira use this library,when connecting,it always use port 443 ,i cant change it.

``` node
let jira = new JiraClient({ 
        host: '192.168.1.111',
        port: '8080',
        basic_auth: {  
                username: process.env.HUBOT_JIRA_USER,
                password: process.env.HUBOT_JIRA_PASS
        }
});
```

when i run it

```
ERROR!
{ Error: connect ECONNREFUSED 192.168.1.111:443
  at Object.exports._errnoException (util.js:1008:11)
  at exports._exceptionWithHostPort (util.js:1031:20)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.1.111',
  port: 443 }
```

please help.

**Comment by yamazakei321** [comment]
Sorry,my fault.

**Comment by rjgoldsborough** [comment]
@yamazakei321 try using an int for the port. 8080 vs '8080'.

I would also try adding a "protocol: 'http'" option. 
jira-connector defaults to https which is probably why you're see the 443.
